### ISSUE TITLE
How can we get the matrix A ?

### ISSUE THREAD

**Issue by oldrive** [yusufdalva/VecGAN#1]
Hi there!

Thank you so much for such wonderful repo, appreciate your efforts!

Can you tell me how to get and randomly init the matrix A?

Any help will be appreciated, Thanks in advance!!

**Comment by oldrive** [comment]
From the supplementary material of VecGAN, I find the Conv1x1 layer after the last DownBlock and before the first UpBlock, the channel is 2048 just same as the feature vector e.

"For the feature encoding and feature directions in matrix A, we use a 2048 dimensional vector representation same as the channel size of the last convolutional layer from the encoder." Can you help me to understand the statement?

Thanks!!

**Comment by yusufdalva** [comment]
Hi,
In the implementation of the study, we initialize matrix A using `nn.Parameter` module from PyTorch, the line defining this matrix is as follows:
`self.direction_matrix = nn.Parameter(data=(1.0 if random_init else 0.001) * torch.randn(size=(len(self.tags), self.latent_dim)), requires_grad=True)`

For the role of the last 1x1 convolution, we wanted to give the flexibility to change the dimensionality of the global vector representing the image. Other than that, we did not encounter any additional benefit.

We are trying our best to prepare the implementation for release. We will release the code, together with the checkpoints, shortly.

Thanks!

**Comment by oldrive** [comment]
But the dimension of the last downblock's output has been reduced to 2048×1×1(the image size is 256x256). Isn't the dimension of e(e = E(x)) 2048×1? Why do we need to use a separate convolution layer to change dimensions? If it changes,  how should the dimension change?

If there is anything wrong with me, please correct it!

**Comment by yusufdalva** [comment]
The dimension is still the same after the convolutional layer, but to translate the vector e, we reshape the vector with the view operation (from 2048x1x1 to 2048x1). The last convolution has no effect on the dimensions in the final model (2048x1x1 to 2048x1x1). The last convolution only gives the opportunity to shrink the latent vector e if desired.

**Comment by oldrive** [comment]
I get it, thanks!!
