### ISSUE TITLE
Semantic direction of non-binary attribute

### ISSUE THREAD

**Issue by oldrive** [yusufdalva/VecGAN#2]
From the video on your project page, we can see that there is a semantic direction of hair color according to the principle of attribute label hierarchical design. Hair color is a non-binary attribute, but the semantic direction is the normal vector of the binary attribute hyperplane from InterfaceGAN. So, why the learned semantic direction of hair color can guide the model to edit three different hair colors (blond, black, brown)? Or these three hair colors can be regarded as a binary attribute to some extent?

Can you help me solve these problems? Thanks!!!

**Comment by yusufdalva** [comment]
Hi,
In our definition, we apply the translations using a continuous scale, defining it as line segments for each attribute. For the case of hair color, we have three intervals where we sample the feature strength with the order black, brown, and blond, respectively. To define such logical intervals, we define four different endpoints as learnable parameters where the interval between endpoint[i] and endpoint[i + 1] defines the line segment for attribute i (for example line segment corresponding to black hair color is defined by endpoint[0] and endpoint[1], where the scale is defined with a z drawn from a uniform distribution as we mention in the paper). This way, we aimed to achieve a continuous distribution for scales of different semantics.

**Comment by oldrive** [comment]
I get it, thanks!!
