### ISSUE TITLE
Time when the code release

### ISSUE THREAD

**Issue by MZMMSEC** [yusufdalva/VecGAN#3]
Hi, great job! I wonder when do you plan to release your code implementation for study?

Thanks!

**Comment by yusufdalva** [comment]
Hi,
I am currently applying the final edits to the implementation of the extended version to make it suitable for a release. The code will be available within 3-4 weeks.

Thanks for your patience!

**Comment by ManuelRios18** [comment]
Hello @yusufdalva any updates on this?

**Comment by yusufdalva** [comment]
Hi,
The inference code for a single image is available now.
Thanks again for your patience!
