### ISSUE TITLE
Running inference example

### ISSUE THREAD

**Issue by gebaltso** [yusufdalva/VecGAN#4]
Could you please provide an example of running inference with all arguments names? Thanks in advance

**Comment by yusufdalva** [comment]
Hi,

Here you can find an example for running the code with tag 5 (smile) and attribute 1 (without) with a z value of 0.4. This transformation will apply the effect of "remove the smile". For the other tags, 1 is for eyeglasses, 2 is for hair color, 3 is for age, 4 is for gender. You can find the associated tags in the config file provided.

Below is an example script to run the inference code for a given image (latent-guided mode).

```
DEVICE="cuda"
CONFIG_PATH="config/model_config.py"
CHECKPOINT_PATH="checkpoints/gen_00420000.pt"
INPUT_PATH="samples/smile/input/1881.jpg"
OUTPUT_PATH="samples/smile/output"
MODE="l"
TAG="5"
ATTRIBUTE="1"
Z="0.4"

python inference.py --device $DEVICE \
                    --config_path $CONFIG_PATH \
                    --checkpoint_path $CHECKPOINT_PATH \
                    --input_path $INPUT_PATH \
                    --output_path $OUTPUT_PATH \
                    --mode $MODE \
                    --tag $TAG \
                    --attribute $ATTRIBUTE \
                    --z $Z
```

The output that I got on this example is also provided as https://github.com/yusufdalva/VecGAN/blob/main/samples/smile/output/1881_out_tag%3A5_attr%3A1_z%3A0.4.jpg
